baseurl: "/homepage" 
url: "https://wangjianli123.github.io"
theme: jekyll-theme-hacker
exclude: LICENSE.txt
      README.md
      _pages 
email: wangjianli_123@163.com
#description: Jian-Li Wang
github_username: wangjianli123
duoshuo_shortname: jlwang
permalink: /:title/
markdown: kramdown
port: 4001
