baseurl: "/homeoage" 
url: "https://wangjianli123.github.io"
theme: jekyll-theme-hacker
email: wangjianli_123@163.com
description: Jian-Li Wang
github_username: wangjianli123
duoshuo_shortname: jlwang
permalink: /:title/
markdown: kramdown
port: 4001
